version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "3377:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # soketi:
  #   image: quay.io/soketi/soketi:1.4-16-debian
  #   container_name: soketi
  # environment:
  #   DEBUG: 1
  #   SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
  #   DEFAULT_APP_ID: ${PUSHER_APP_ID}
  #   PUSHER_APP_ID: ${PUSHER_APP_ID}
  #   SOKETI_DEFAULT_PUSHER_APP_ID: ${PUSHER_APP_ID}
  #   DEFAULT_PUSHER_APP_ID: ${PUSHER_APP_ID}
  #   APP_ID: ${PUSHER_APP_ID}
  # SOKETI_DEFAULT_APP_KEY: f11641c90a9b3766d481
  # SOKETI_DEFAULT_APP_SECRET: 6d4ece935cfbffc32e2b
  #   PUSHER_HOST: 127.0.0.1
  #   PUSHER_PORT: 6001

  # ports:
  #   - "6001:6001"
  #   - "9601:9601"
volumes:
  postgres-data:
