import Link from "next/link";

export default function JoinCriteriaPage() {
  return (
    <>
      <header className="site-header">
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <p className="tagline">Join Artisanal Futures</p>
            <h1>Criteria for Joining Artisanal Futures</h1>
          </div>
        </div>
      </header>

      <section className="site-section prose prose-sm lg:prose-base">
        <p>
          We are primarily small scale, “mom and pop” enterprises, where the
          workers are the owners. We also welcome large scale worker
          cooperatives, as long as the majority of workers are owners, and
          vice-versa. Our goal is to enable an economy where people are doing
          what they love, under the conditions that work best for them. We want
          to minimize the extraction by external corporations. We want to
          maximize the circulation of value generated by workers, and the places
          in which they live, back to those workers and living environments and
          communities.
        </p>

        <p>
          Worker cooperatives are defined by the{" "}
          <Link href="https://ica.coop/" target="_blank">
            International Cooperative Alliance
          </Link>{" "}
          as meeting the following criteria:
        </p>
        <ol>
          <li>
            They have the objective of creating and maintaining sustainable jobs
            and generating wealth, to improve the quality of life of the
            worker-members, dignify human work, allow workers&apos; democratic
            self-management and promote community and local development.
          </li>
          <li>
            The free and voluntary membership of their members, in order to
            contribute with their personal work and economic resources, is
            conditioned by the existence of workplaces.
          </li>
          <li>
            As a general rule, work shall be carried out by the members. This
            implies that the majority of the workers in a given worker
            cooperative enterprise are members and vice versa.
          </li>
          <li>
            The worker-members&apos; relation with their cooperative shall be
            considered as different from that of conventional wage-based labor
            and to that of autonomous individual work.
          </li>
          <li>
            Their internal regulation is formally defined by regimes that are
            democratically agreed upon and accepted by the worker-members.
          </li>
          <li>
            They shall be autonomous and independent, before the State and third
            parties, in their labor relations and management, and in the usage
            and management of the means of production
          </li>
        </ol>

        <h2>We Do Not Accept:</h2>

        <ol>
          <li>
            No corporations like Walmart. That excludes both chain businesses,
            like Chipotle, where the parent company owns each location, and
            franchise business like McDonald&apos;s, where different stores or
            branches are owned by separate individuals. Both are not eligible,
            because the workers are not the owners.
          </li>
          <li>
            No corporations pretending to be a co-op. For example, “REI Coop” is
            misusing the word. They are not a worker cooperative. They are just
            a company that offers the consumers a membership, just for discount,
            like Costco or Sam&apos;s club.
          </li>
          <li>
            No criminal enterprise, obviously, but there are gray areas like
            marijuana, which is legal in Michigan but not by federal law.
            However we don&apos;t know of any marijuana companies that are
            worker-owned.
          </li>
        </ol>
      </section>
    </>
  );
}

export const metadata = {
  title: "Criteria for Joining Artisanal Futures",
};
