import { redirect } from 'next/navigation'

import CookieConsent from '~/components/cookie-banner'
import { getServerAuthSession } from '~/server/auth'
import { api } from '~/trpc/server'
import Navbar from './_components/layout/navbar'

// <Head>
// <title>Solidarity Pathways | Artisanal Futures</title>
// <meta name="description" content="Generated by create-t3-app" />{" "}
// <meta
//   name="viewport"
//   content="width=device-width,height=device-height initial-scale=1"
// />
// <link rel="icon" href="/favicon.ico" />{" "}
// <link rel="manifest" href="/manifest.json" />{" "}
// {/* <link rel="apple-touch-icon" href="/apple-touch-icon.png" />  */}
// </Head>

export const metadata = {
  title: 'Solidarity Pathways',
}
type Props = {
  children: React.ReactNode
}
export default async function RouteLayout({ children }: Props) {
  const session = await getServerAuthSession()

  if (!session || !session.user) {
    return redirect('/tools/solidarity-pathways/sandbox')
  }

  const depot = await api.depots.getCurrentDepot()

  if (depot && !window.location.pathname.includes(depot.id)) {
    return redirect(`/tools/solidarity-pathways/${depot.id}/overview`)
  }

  return (
    <>
      <main className="fixed flex h-full w-full flex-col ">
        <Navbar />
        <div className="relative flex h-full  flex-col-reverse  bg-slate-50 p-2  max-md:overflow-auto md:flex-row lg:h-[calc(100vh-64px)]">
          {children}
        </div>
        <CookieConsent />
      </main>
    </>
  )
}
